language: python

python: 
  - 3.8
  
sudo: required

before_install:
  - pip install -U pip
  - echo "Testing"
  
install:
  - pip install -r requirements.txt
  
script:
  - pytest
  
after_success:
  - echo "Test Success"
