language: python

python: 
  - 3.8
  
install:
  - pip install -r requirements.txt
  
script:
  - pytest

before_install:
  - pip install -U pip
  - pip uninstall setuptools
  - pip install 'setuptools<20.2'
  - echo "Testing"
  
after_success:
  - echo "Test Success"
