language: python

python: 
  - 3.7

env:
  global:
    - PACKAGENAME="octavia\init.py"


install:
- python setup.py install

script:
- pytest $PACKAGENAME

before_install:
  - echo "Testing"
  
after_success:
  - echo "Test Success"
