language: python

python: 
  - 3.7

env:
  global:
    - PACKAGENAME="code"


install:
- python setup.py install

script:
- python setup.py test

before_install:
  - echo "Testing"
  
after_success:
  - echo "Test Success"
